# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYLGahMwRicz9oYNGiFa2HX8KD89yB67
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# قراءة الـModel
try:
    loaded_model = joblib.load("kmeans.pkl")
    st.success("Model loaded successfully!")
except FileNotFoundError:
    st.error("Error: The model file 'AgglomerativeClustering.pkl' was not found.")
    st.stop()

st.title("Customer Segmentation Application")
st.write("Enter the customer's spending data to find their segment.")

features_columns = ['Fresh', 'Milk', 'Grocery', 'Frozen', 'Detergents_Paper', 'Delicassen']

input_values = {}
for col in features_columns:
    input_values[col] = st.slider(f"Enter spending on {col}", min_value=0, max_value=100000, value=5000)

if st.button("Predict Customer Segment"):
    input_data = pd.DataFrame([input_values])

    prediction = loaded_model.fit_predict(input_data)

    st.header("Prediction Result")
    st.success(f"This customer belongs to Cluster: **{prediction[0]}**")

